### ISSUE TITLE
一週年

### ISSUE THREAD

**Issue by RexYuan** [RexYuan/courseNTNU#45]
:fireworks: 剛好過了整整十二個月自從這個上線了！

截至我剛剛看為止（2015/12/19 00:00），我們總共累積了 2207 個投票（改版前 1950 改版後 257 可能重複）、168,700 個瀏覽量。我自認為這樣很不錯－至少遠比我開始之前預料到的多非常多！

分享一些這一年的圖表：
![screen shot 2015-12-19 at 12 05 07 am](https://cloud.githubusercontent.com/assets/5001650/11901111/c8403b9a-a5e4-11e5-97c0-f842c66cf7b3.png)
![screen shot 2015-12-19 at 12 05 22 am](https://cloud.githubusercontent.com/assets/5001650/11901120/cc6c2134-a5e4-11e5-84f3-8961c30c7748.png)
![screen shot 2015-12-19 at 12 05 33 am](https://cloud.githubusercontent.com/assets/5001650/11901121/ce3a2754-a5e4-11e5-8307-76403e361dbe.png)

不過，因為這是動態網站（我自己架的也覺得滿有意思，是第一次接觸 Linux），我已經花了131.18 美金（12*10+10+1.18），希望之後有機會可能找到人贊助，不過仔細想想後，我覺得就算是改成靜態網站，有效地呈現資料就已經夠棒了ㄏㄏ！

我就不細數事蹟了，但我真的得感謝 @wi1d5ky 跟 @jaidTw 你們的幫忙！ :smiley:

**Comment by wildskyf** [comment]
\OwO/

Chih-cheng Yuan notifications@github.com於 2015年12月19日 週六，00:16寫道：

**Comment by jaidTw** [comment]
course需要高手來幫忙啊~~
